### ISSUE TITLE
Organize oyster samples in -80

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-oyster-oa#1]
We finally have a data sheet
https://github.com/RobertsLab/project-oyster-oa/tree/master/data

so now vials can be nicely organized in freezer boxes, so we can determine which samples to start processing.

Probably would be helpful to develop a simple map to indicate where sites are.

**Comment by yaaminiv** [comment]
I have a basic idea of how I would like to organize the vials. I can meet Monday to discuss and get started.

![Really rough idea of vial organization](https://cloud.githubusercontent.com/assets/22335838/19008811/c1810b16-8722-11e6-825f-398aa82dd38c.jpg)

**Comment by yaaminiv** [comment]
I was mistaken and I believe we are missing samples from Round 1 of the experiment (vials O1-O149). I organized all of the samples from Round 2 already and they are in the -80. I will search more thoroughly through the -80 later today, but I already went through a good chunk of it and all of the boxes that aren't labelled don't have our samples.

**Comment by yaaminiv** [comment]
All samples have officially been located and organized into 4 separate boxes, as detailed in the above schematic!
