### ISSUE TITLE
Opening new Skyline file?

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-oyster-oa#10]
I presume 

step 2a 1 
https://github.com/RobertsLab/project-oyster-oa/blob/master/notebooks/DNR/2017-09-28-SRM-Skyline-Data-Pipeline.ipynb

refers to "Blank Document"?

![image](https://user-images.githubusercontent.com/4442039/31294378-84be1e30-aa8f-11e7-8dca-512584abc07a.png)

**Comment by yaaminiv** [comment]
Yes! I'll update the protocol accordingly.
