### ISSUE TITLE
Source of blib?

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-oyster-oa#11]
What is `2017-05-23-oyster-desearleinated.blib` ?

Where did it come from.

place short explanation on protocol

https://github.com/RobertsLab/project-oyster-oa/blob/master/notebooks/DNR/2017-09-28-SRM-Skyline-Data-Pipeline.ipynb

**Comment by yaaminiv** [comment]
From my [lab notebook](https://yaaminiv.github.io/Skyline-Attempt-3/):

> Emma and her team were able to figure out that brecan (a version of pecanpie produced by Brian Searle in Genome Sciences) “produces blib files that have a certain number of incompatibilities with Skyline (one of which is redundant peptide identifications). Jarrett Egertson wrote a script to get rid of these incompatibilities so that the brecan blib files work,” (Timmins-Schiffman, pers. comm.)

Essentially Emma made my original .blib while I was going through my DIA analyses and I found that there were extremely high error rates in my Skyline document. So someone fixed the problem and created a new .blib using a version of PECAN. I don't have the script but can ask for it.

**Comment by sr320** [comment]
again be sure to add in protocol

**Comment by yaaminiv** [comment]
Will do.

**Comment by yaaminiv** [comment]
Protocol updated accordingly 
<img width="780" alt="screen shot 2017-10-10 at 2 14 04 pm" src="https://user-images.githubusercontent.com/22335838/31411068-4d388476-adc5-11e7-858e-1398323e83ba.png">
