### ISSUE TITLE
Issue at Step 2f

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/project-oyster-oa#12]
It's a little unclear how this step should be performed.

All the RAW files are on OWL. I can't figure out how to navigate to the directory, select, and open. 

It seems like your protocol is saying that I should be able to navigate to the directory from the window that pops up after selecting, "Ok" in the "Import Results" window. 
![capture5](https://user-images.githubusercontent.com/14934314/31414636-c20168e6-add3-11e7-966f-451fe12a4332.PNG)

After searching around, it's not there. Am I supposed to do it somehow from the browser that the OWL folder is open in?

Maybe this is happening because this computer is brand new...?

**Comment by yaaminiv** [comment]
Probably should clarify that in step 1 when you're gathering your materials, you should download the raw files. I can write some code and put that in to make it easier. 

Basically what you need to do is download the raw files from the OWL link provided and then proceed with 2f!

**Comment by yaaminiv** [comment]
@grace-ac were you able to download the files? i'm working on some code but it could take a while since i'm a bit rusty

**Comment by yaaminiv** [comment]
@grace-ac JK not as rusty as I thought. Try this to download all RAW files from OWL:

`wget --no-parent -r http://owl.fish.washington.edu/spartina/DNR_SRM_20170728/Raw-Files/`

**Comment by kubu4** [comment]
@yaaminiv - She won't be able to do that since there's no command line tool installed on the Windows machine(s).

@grace-ac - The easiest way for you to currently do this is to log in to Owl. Use the "File Station" thing on Owl to navigate to the directory with all of the raw files. Select all of the files, right-click, Download.

**Comment by sr320** [comment]
Actually I already fixed this but possibly my edits were overwritten?

**Comment by yaaminiv** [comment]
@sr320 Probably. I didn't realize you edited the file so I didn't sync the document with the version in the cloud before I continued editing.

**Comment by yaaminiv** [comment]
@sr320 Went through and restored your edits. This is now fixed and @grace-ac should be able to access the .zip with all raw files

**Comment by sr320** [comment]
There is flaw here if used the desktop client or command line

It would have caught this

![2130c18d-8b0d-48c8-bd00-0680e100a83e](https://user-images.githubusercontent.com/4442039/31415524-dc38120a-add8-11e7-9dae-e471157d6cd8.jpeg)

Need to check flow

**Comment by yaaminiv** [comment]
That's all me. Normally if there are multiple people working on a repo I sync before I make edits on any desktop files. Didn't realize you were also making edits on this repo, or else I would have synced before I edited!

**Comment by sr320** [comment]
I guess my point is that you should not have needed to sync. If there was a
conflict the software would have not allowed you to commit?

Unless you were in a web browser and cut and paste new text?

We should figure this out as it does introduce “issues” :)

**Comment by kubu4** [comment]
Hmmm, I'm not sure there's anything for Git to catch here. There aren't any conflicts in that image above.

I think the only way to avoid these types of problems is to eliminate collaborator status. Then, any changes have to be submitted as pull requests, which allows the repo admin to allow/deny changes.

**Comment by sr320** [comment]
Yep, you are probably right.

**Comment by grace-ac** [comment]
So using think at the top of your notebook entry, the RAW files were downloaded into a zip called "Archive". On the computer, I can see them in the srlab>downloads folder, and when I open the folder, they are all there.

However, when trying to follow step 2f in Skyline Daily, the folder and the files are not in the srlab-downloads.... ? 
![capture](https://user-images.githubusercontent.com/14934314/31467737-d8327314-ae8f-11e7-9050-4847514bed11.PNG)

Apologies if I'm missing something- I tried reading through all of these comments above.

**Comment by yaaminiv** [comment]
In the Import Results Files, you have Sources of type set to "Any spectra format". Try changing it so it includes all filetypes?

**Comment by sr320** [comment]
This might be related to a “feature” in Windows- you can see the files in the zip file without unzipping. Try unzipping/uncompressing - maybe double click or right click on .zip file.

**Comment by yaaminiv** [comment]
@grace-ac Your issue is related to @sr320's comment. I unzipped the Archive so you can now access the RAW files from Skyline
