### ISSUE TITLE
Include Software version numbers 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-oyster-oa#13]
in 
https://github.com/RobertsLab/project-oyster-oa/blob/master/notebooks/DNR/2017-09-28-SRM-Skyline-Data-Pipeline.ipynb

**Comment by yaaminiv** [comment]
<img width="513" alt="screen shot 2017-10-11 at 2 07 36 pm" src="https://user-images.githubusercontent.com/22335838/31466869-9188a926-ae8d-11e7-817f-459220d2e251.png">

Resolved.
