### ISSUE TITLE
Add what a blib file is...

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-oyster-oa#14]
1 sentence is fine

https://github.com/RobertsLab/project-oyster-oa/blob/master/notebooks/DNR/2017-09-28-SRM-Skyline-Data-Pipeline.ipynb

**Comment by yaaminiv** [comment]
<img width="944" alt="screen shot 2017-10-11 at 2 10 29 pm" src="https://user-images.githubusercontent.com/22335838/31467212-0f0f5868-ae8e-11e7-8c08-35697a4a70c6.png">

Resolved.
