### ISSUE TITLE
Step 2C 2 - Exclude N-terminal AAs?

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-oyster-oa#15]
Value is not explicitly stated 
but in the screen shot is 0, by default it is no. Should it be?

![image](https://user-images.githubusercontent.com/4442039/31449398-a73c128a-ae5b-11e7-89c6-e43540cc1a39.png)

https://github.com/RobertsLab/project-oyster-oa/blob/master/notebooks/DNR/2017-09-28-SRM-Skyline-Data-Pipeline.ipynb

**Comment by yaaminiv** [comment]
It should be 0. I'll update the protocol accordingly.

**Comment by yaaminiv** [comment]
<img width="981" alt="screen shot 2017-10-11 at 2 12 20 pm" src="https://user-images.githubusercontent.com/22335838/31467262-39e22534-ae8e-11e7-8d1e-39138bb7dda8.png">

Resolved.
