### ISSUE TITLE
Importing Data step 2f

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-oyster-oa#16]
It is not clear which files to import.

all 171 ?

https://github.com/RobertsLab/project-oyster-oa/blob/master/notebooks/DNR/2017-09-28-SRM-Skyline-Data-Pipeline.ipynb

**Comment by yaaminiv** [comment]
> The dilution curve files are labelled "D#-O," where "D" stands for "dilution", # represents which dilution ratio was used, and "O" stands for "oyster." There are eight dilution files. Select files to import and click "Open".

You'd only import the 8 dilution curve files

**Comment by sr320** [comment]
So change to Import Dilution curve files

**Comment by sr320** [comment]
It would maybe seem more intuitive if this was part of Step 3?

**Comment by yaaminiv** [comment]
<img width="1004" alt="screen shot 2017-10-11 at 2 14 15 pm" src="https://user-images.githubusercontent.com/22335838/31467343-7d5ff6ce-ae8e-11e7-9df7-5d37396b01c3.png">

Resolved.
