### ISSUE TITLE
No peaks? Step 3a.

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-oyster-oa#17]
see http://d.pr/v/X0RRmR

Step 3a, I am not seeing anything

Only deviation was I was importing all files. I cancelled.
Closed Skyline, re-opened and opened my setting file saved in Step 2

**Comment by yaaminiv** [comment]
Ah, okay I see your analyte tree is full of all proteins. Since we only
targeted a select few, you won't have any data for the vast majority of
proteins there. I believe I deleted proteins that weren't targets by hand,
but I'll finalize instructions and put them on the protocol. Forgot I did
that!

**Comment by sr320** [comment]
Probably makes sense to just import targets at fasta stage and not complete protein bank.

**Comment by yaaminiv** [comment]
Agreed, I'll adjust accordingly.

**Comment by yaaminiv** [comment]
<img width="975" alt="screen shot 2017-10-11 at 9 06 12 pm" src="https://user-images.githubusercontent.com/22335838/31478852-137c44e4-aec8-11e7-98e4-3e83e4510bab.png">
<img width="512" alt="screen shot 2017-10-11 at 9 06 23 pm" src="https://user-images.githubusercontent.com/22335838/31478854-1482be9a-aec8-11e7-8dc9-8fee6c2c2836.png">

Resolved.
