### ISSUE TITLE
Correlating technical replicates

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/project-oyster-oa#18]
As @emmats suggested, I regressed my technical replicates against each other for each transition to see if some transitions were messier than others. You can see my work in my [lab notebook entry](https://yaaminiv.github.io/Correlating-Technical-Replicates/).

There are definitely some transitions with lower adjusted R squared values than others. My first instinct is to establish some sort of R-squared cutoff, remove transitions lower than this cutoff, and then remake my NMDS plot. While I'm going through each transition, I can also see if there are certain outliers or leverage points that could be influencing the R-squared values (for those close to the cutoff).

Any suggestions for what that cutoff should be?

**Comment by emmats** [comment]
What is the range? I would go pretty high with the cut-off. Your replicates should be right on top of each other. Maybe have @laurahspencer run the same script and figure out what her range of R2 values are? Off the cuff, I would say cut-off should be at least 0.85.

**Comment by yaaminiv** [comment]
The range is .2 to .9 (there are examples of each in my notebook), with the majority being above 0.6.

**Comment by yaaminiv** [comment]
Some examples for context. Peak area from the first batch of technical replicates on the x-axis, peak area from the second batch of technical replicates on the y-axis. Points are labelled with the oyster sample ID.

![bad-R](https://raw.githubusercontent.com/RobertsLab/project-oyster-oa/master/analyses/DNR_SRM_20170902/2017-10-10-Troubleshooting/2017-10-10-Transition-Replicate-Correlations/CHOYP_ACAA2.1.1%7Cm.30666%20ELGLNNDITNMNGGAIALGHPLAASGTR%20y12%20.jpeg)

![good-R](https://raw.githubusercontent.com/RobertsLab/project-oyster-oa/master/analyses/DNR_SRM_20170902/2017-10-10-Troubleshooting/2017-10-10-Transition-Replicate-Correlations/CHOYP_G6PD.2.2%7Cm.46923%20SDELYEAWR%20y5%20.jpeg)

**Comment by sr320** [comment]
To me it should be some defined range around a line that is has slope of 1. 
Thus based on replicates and not proteins

**Comment by laurahspencer** [comment]
I did a quick work-up using Yaamini's script. Summary data for R^2:
  * Mean: 0.8636
  * Min^: 0.6507
  * Max: 0.9679
  * Median: 0.9016
^One peptide from Superoxide Dismutase had an awful R^2 for 2 transitions (<0.1), which were outliers.

NOTE: This wasn't using the full data set. I have 17 samples with 3 reps, and 3 samples with 4 reps; only the first 2 reps run are represented here, which likely skews things a bit (didn't want to dig too deep into modifying the code).

**Comment by yaaminiv** [comment]
@emmats Maybe I can start with a 0.65 R-squared cutoff. If that doesn't improve anything, work up to a 0.85 cutoff?

@sr320 can you elaborate on your suggestion? From what I understand, I would plot x = y line in addition to a linear regression, and then consolidate the two somehow?

**Comment by sr320** [comment]
Lets discuss in class

**Comment by emmats** [comment]
I think the 0.6 cut-off sounds safe. But, of course, @sr320 makes the final call.

This is pretty informative for me. I've never done this before.

**Comment by yaaminiv** [comment]
@emmats Here's my plan:

1. Normalize all my values by TIC to reduce any external variation (the plots I've made so far are not normalized...what are your thoughts on this step?)
2. Use a 0.6 cutoff and discard any transitions with an adjusted R-squared value below this. Remake an NMDS plot and examine clustering

AT THE SAME TIME...

1. Plot an x = y line on each plot, as well as a 95% confidence interval. @sr320 and I discussed the value of this during class. Since our technical replicates should have the same protein abundances, we expect the best fit model to be a 1:1 ratio.
2. Discard transitions with less than 95% of the points (43 points) within the condense interval. Remake an NMDS plot and examine clustering

Thoughts?

**Comment by emmats** [comment]
I think that sounds good. I don't think you need to normalize by TICs. If your TICs vary widely between technical replicates, then you have other problems.

**Comment by yaaminiv** [comment]
@emmats @sr320 
[Notebook]()

I went through the first part of my plan and used R-squared cutoffs to eliminate transitions and remake NMDS plots. I used a combination of three cutoffs (0.6, 0.7 and 0.8) and normalized/nonnormalized data. I found normalizing made my plots look a little better. Overall this helped a bit, but the technical replication still doesn't look fantastic.

0.6, normalized:

![0.6-normalized-NMDS](https://raw.githubusercontent.com/RobertsLab/project-oyster-oa/master/analyses/DNR_SRM_20170902/2017-10-10-Troubleshooting/2017-10-10-Transition-Replicate-Correlations/2017-10-13-NMDS-TechnicalReplication-Normalized-Cutoff1.jpeg)

![0.6-normalized-distances](https://raw.githubusercontent.com/RobertsLab/project-oyster-oa/master/analyses/DNR_SRM_20170902/2017-10-10-Troubleshooting/2017-10-10-Transition-Replicate-Correlations/2017-10-13-NMDS-TechnicalReplication-Ordination-Distances-Normalized-Cutoff1.jpeg)

0.7, normalized:

![0.7-normalized-NMDS](https://raw.githubusercontent.com/RobertsLab/project-oyster-oa/master/analyses/DNR_SRM_20170902/2017-10-10-Troubleshooting/2017-10-10-Transition-Replicate-Correlations/2017-10-13-NMDS-TechnicalReplication-Normalized-Cutoff2.jpeg)

![0.7-normalized-distances](https://raw.githubusercontent.com/RobertsLab/project-oyster-oa/master/analyses/DNR_SRM_20170902/2017-10-10-Troubleshooting/2017-10-10-Transition-Replicate-Correlations/2017-10-13-NMDS-TechnicalReplication-Ordination-Distances-Normalized-Cutoff2.jpeg)

0.8, normalized:

![0.8-normalized-NMDS](https://raw.githubusercontent.com/RobertsLab/project-oyster-oa/master/analyses/DNR_SRM_20170902/2017-10-10-Troubleshooting/2017-10-10-Transition-Replicate-Correlations/2017-10-13-NMDS-TechnicalReplication-Normalized-Cutoff3.jpeg)

![0.8-normalized-distances](https://raw.githubusercontent.com/RobertsLab/project-oyster-oa/master/analyses/DNR_SRM_20170902/2017-10-10-Troubleshooting/2017-10-10-Transition-Replicate-Correlations/2017-10-13-NMDS-TechnicalReplication-Ordination-Distances-Normalized-Cutoff3.jpeg)

I'll try the second part soon, but it may take me a bit longer since making a confidence interval around a line in a for loop is a bit more tedious. Any thoughts about these results?

**Comment by sr320** [comment]
I would not necessarily expect r2 threshold to improve reps- eg you good
have a r2 of 1 and slope could be 0.

**Comment by emmats** [comment]
I'm still pretty suspicious of these data. It just doesn't make sense that the technical replicates don't look the same.

**Comment by sr320** [comment]
@yaaminiv can you please provide a csv with respective technical in adjacent columns?

**Comment by yaaminiv** [comment]
@sr320 [csv](https://github.com/RobertsLab/project-oyster-oa/blob/master/analyses/DNR_SRM_20170902/2017-10-10-Troubleshooting/2017-10-24-Confidence-Interval-Transitions/2017-10-24-Targets-Replicates-Adjacent-Columns.csv)

I just tried playing with slopes and confidence intervals. I'm going to try one more thing on that front and then write it up in a lab nb post/possibly post a new issue

**Comment by yaaminiv** [comment]
[Notebook](https://yaaminiv.github.io/Correlating-Technical-Replicates-Part3/)

I was following @sr320 suggestion to look at slopes and plot a 95% confidence interval around an x = y line. Ran into some issues doing that (more details in my nb), so I can only really plot an x = y line and a prediction line (same intercept as regression, but a slope of 1) along with my data.

![example](https://raw.githubusercontent.com/RobertsLab/project-oyster-oa/master/analyses/DNR_SRM_20170902/2017-10-10-Troubleshooting/2017-10-24-Confidence-Interval-Transitions/CHOYP_ACAA2.1.1%7Cm.30666%20ITGHLAHELQR%20y7%20confint.jpeg)

Any suggestions for how to move forward? A few of my issues are that there are large intercepts for the regression, so an x = y line is far removed and creating a confidence interval around an x = y line/prediction line is essentially impossible with my skill set because neither or those have any error (so plotting a CI would just lead to an upper and lower bound falling directly on top of the original line). I could look at the slope of the original regression and if it falls within some cutoff (1 ± some undetermined error value), I remove the transition and remake an NMDS?

Thoughts? (esp from @emmats since you think this data is suspicious?) I'm stumped, and the only thing I think may work now might be rerunning samples (but I don't know how possible that is)...

**Comment by yaaminiv** [comment]
There are also transitions that have poor R squared values but slopes close to 1. What should I do about those?

![choyp_psa 1 1 m 27259 yfqiayplpk y4 confint](https://user-images.githubusercontent.com/22335838/31961321-3d222c32-b8af-11e7-9735-19268b06278b.jpeg)

**Comment by sr320** [comment]
Provide the new data sheet I mentioned above and I can provide feedback

**Comment by yaaminiv** [comment]
@sr320 The one with tech reps in adjacent columns? I linked you to that!

**Comment by sr320** [comment]
Sorry - I need it in just two columns with the sample IDs in a column...

**Comment by yaaminiv** [comment]
@sr320 I think I'm confused...so sample IDs in one column, transitions in another column?

**Comment by sr320** [comment]
Col1-transition     |      Col2-sampleID     |      Col3-rep1      |      Col4-rep2

**Comment by sr320** [comment]
Column1 and Column2 could be switched....

**Comment by yaaminiv** [comment]
normalized or not normalized?

**Comment by sr320** [comment]
How about both...

**Comment by yaaminiv** [comment]
[Normalized](https://github.com/RobertsLab/project-oyster-oa/blob/master/analyses/DNR_SRM_20170902/2017-10-24-Normalized-Adjacent-Technical-Replicates)
[Not normalized](https://github.com/RobertsLab/project-oyster-oa/blob/master/analyses/DNR_SRM_20170902/2017-10-24-NonNormalized-Adjacent-Technical-Replicates)

**Comment by sr320** [comment]
Use this data to start making graphs - simply average reps. 

http://d.pr/f/OtdTD

This is just the normalized data with coefficient of variance less than 20.

**Comment by yaaminiv** [comment]
[Notebook](https://yaaminiv.github.io/Correlating-Technical-Replicates-Part5/)

Used CV filtering to redo NMDS/ANOSIM analyses. Slight improvement in technical replication, ANOSIM/NMDS indicates no significant clustering pattern.

Going to filter data with CV ≤ 10 and repeat. Will also look at expression of individual proteins making boxplots, etc. Interested in your thoughts @emmats.

**Comment by yaaminiv** [comment]
Seeing how we've answered my original question, I'm going to continue the current conversation in #35.
