### ISSUE TITLE
L's feedback to date

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/project-oyster-oa#19]
### 1) Transitions list link in jupyter notebook is broken: 
![image](https://user-images.githubusercontent.com/17264765/31479992-05a23970-aed0-11e7-9da8-d89b316ed91e.png) 

### 4) This might be alarming to someone not used to Skyline, could add a note to protocol:
![y-test3](https://user-images.githubusercontent.com/17264765/31479032-7b25c204-aec9-11e7-97fd-4d7bf92ed398.PNG)

### 3) You could reduce your .fasta used in the SRM Skyline doc to only include target proteins. As is, there isn't a step in the protocol where you remove the proteins (from targets pane) not targeted in SRM, so when importing .raw data it takes much longer than it would with just the target peptides populating the analyte tree, and without going through each protein to check for chromatograms I don't know which proteins are my target (maybe you know a Skyline trick to unfold only proteins w/ peaks???)
![image](https://user-images.githubusercontent.com/17264765/31480726-5671c65a-aed4-11e7-8005-e6dd4dcee9f7.png)

### 5) Step 7b in the protocol has me duplicate/edit the sequence file; could instruct user to use this edited file in your R script:
![image](https://user-images.githubusercontent.com/17264765/31480102-a86fefa8-aed0-11e7-9cf2-6cdb888a031c.png)

### 6) Error merging biological data to abundance data; possibly b/c the column name in biol. data set isn't exactly "Sample.Number"
![image](https://user-images.githubusercontent.com/17264765/31480389-72c29eb2-aed2-11e7-8857-9e9ddf75f55f.png)
### After changing that column's name to "Sample.Number" I executed the merge, but dataframe is empty; I think it's b/c your X db doesn't include sample numbers w/o replicates: 
![image](https://user-images.githubusercontent.com/17264765/31480665-ec403528-aed3-11e7-8c38-98a209c5a424.png)
![image](https://user-images.githubusercontent.com/17264765/31480654-da07cea2-aed3-11e7-893a-c30d623264d0.png)

### 7) "Your Sample Key"/"Sequence File" doesn't have any TIC values: 
![image](https://user-images.githubusercontent.com/17264765/31480979-d78a1606-aed5-11e7-91e8-884d32cb4c9e.png)

### ... the merge error (detailed in 6) is causing problems for the rest of the code, so I'll wait until that's fixed to continue working through the scripts.

**Comment by yaaminiv** [comment]
Thanks for the feedback! Addressing 6)....

...I actually didn't get any errors. I was able to run the script with no problems after opening it (nothing saved in my global workspace).

<img width="792" alt="screen shot 2017-10-11 at 11 19 16 pm" src="https://user-images.githubusercontent.com/22335838/31481944-b5c58532-aeda-11e7-8c36-f731d8bbd5d2.png">

I'm assuming you already tried clearing your workspace and running through the code again?

**Comment by yaaminiv** [comment]
1: Link is not broken! Will take you here: https://github.com/RobertsLab/project-oyster-oa/blob/master/analyses/DNR_TransitionSelection_20170707/2017-07-08-Final-Transitions/2017-07-10-SRM-Transitions-With-PRTC.csv
3: Using the linked file above when populating the analyte tree resolves this issue (procedure outlined in Step 2d)
6: See above comment
7: There are two separate files you are referring to here. The "Key for Samples" in the notebook is the file straight off the machine, and it's an .xlsx document. The other sequence file you're referring to is a .csv used in my R script that includes TIC values and only has information for samples used in downstream analyses. I could definitely do a better job at highlighting the differences in Step 1 when I have you gather the materials.
8: Aside from `reshape2` I don't believe I'm using any packages outside of base R (are there some I'm not aware of?!). Having `install.packages` in our code wouldn't affect a user if they already had that package installed. It would just overwrite what already exists. The real question is how to specify the package versions we're using.

I'll take the rest of your feedback and incorporate it into my wording at an hour that doesn't cause me to go cross-eyed 😆

**Comment by yaaminiv** [comment]
See #20, #21, #22, #23, #24, and #25 for further progress.
