### ISSUE TITLE
Step 3b: Retention time qs

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/project-oyster-oa#29]
Up until now, I've been feeling pretty good about picking retention times, but for this peptide, things seem a bit different. 
Screenshot:
![capture](https://user-images.githubusercontent.com/14934314/32015467-0b4e73e2-b976-11e7-96b3-9abc9012fadf.PNG)

Issues:
(1) This peptide started out by looking like 19.7 was about where the best peak was. Then , as I moved through the tabs, there were no peaks at 19.7, but rather 19.4. Now the Retention Time Replicate Comparison figure looks off. Should I try to pick the peaks that are closer to 19.7 even if they're super tiny?

(2) For this peptide, it looks like the Peak Area - Replicate Comparison figure is increasing over tabs, while the previous peptides, it decreased. Could this have something to do with the new "dotp" that's over the bars? What does "dotp" mean? 

(3) For this peptide, there's a "Library" bar in the Peak Area - Replicate Comparison figure. Where did this come from? This wasn't in the previous peptide figures...

**Comment by yaaminiv** [comment]
1) I would pick the peaks at 19.4. Retention times will decrease as you move through the samples and there are bound to be some anomalies.
2) Not exactly sure what dotp means but it's not affecting whether something increases or decreases! That's just the assay, so in this case, this peptide would be something you exclude moving forward (refer to SRM protocol for more information on that).
3) The library bar just means that Skyline recognizes this peptide and it matching it to information it finds in its own database. Some peptides have them, some don't. It's not important!

**Comment by sr320** [comment]
note I am just watching this,  but it would appear that every issue grace
has, needs to be addressed in the protocol itself, not just in github.
Thus the github response would be how the protocol has been changed..

we can go over in class tomorrow.

**Comment by yaaminiv** [comment]
Ah, yes. I've made a note of what needs to be modified in the SRM protocol and have a few ideas/clarifications I'll bring up class!

**Comment by grace-ac** [comment]
New Question:

Skyline picked this after I clicked "Apply Peak to All" in the first tab:
![capture1](https://user-images.githubusercontent.com/14934314/32017810-c19819c2-b97c-11e7-9120-f88ed371c385.PNG)

Should I go through when this happens and pull the boundaries out for the peak like so: 
![capture](https://user-images.githubusercontent.com/14934314/32017830-d1bcc46a-b97c-11e7-9558-52eb2dc420ed.PNG)

Or is that unnecessary?

**Comment by yaaminiv** [comment]
It's necessary (and I believe I mention to fix peak boundaries in the protocol)!

**Comment by grace-ac** [comment]
Ah yes, so sorry! You definitely did!! I see that now.

**Comment by yaaminiv** [comment]
Protocol updated with clearer peak picking instructions.
