### ISSUE TITLE
sampling plan for protein extractions

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/project-oyster-oa#3]
should i just randomly select 10 samples for us to extract proteins from? that would be 1 sample per treatment.

**Comment by sr320** [comment]
Yes- please list out samples here

**Comment by yaaminiv** [comment]
generated using [random number generator](random.org)

ROUND 1:

CI
	bare: O15
	eelgrass: O07
FB
	bare: O47
	eelgrass: O34
PG
	bare: O55
	eelgrass: O77
SK
	bare: O119
	eelgrass: O107
WB
	bare: O127
	eelgrass: O142
