### ISSUE TITLE
Missing some peptides?

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/project-oyster-oa#30]
I'm missing some peptides (Highlighted in orange) in my Skyline list that are listed in your SRM Retention times spreadsheet:
![capture1](https://user-images.githubusercontent.com/14934314/32021575-986acb7e-b988-11e7-8cb4-7cc221ddd55d.PNG)

**Comment by yaaminiv** [comment]
Oof. Okay I'll try and fix that ASAP and let you know when I'm done (hopefully tomorrow)

**Comment by grace-ac** [comment]
@yaaminiv your skyline document in Owl is also missing those same peptides (highlighted in orange if first comment)
![capture](https://user-images.githubusercontent.com/14934314/32067929-a49be8a4-ba39-11e7-818d-70840d209f70.PNG)

**Comment by yaaminiv** [comment]
According to [my notebook](https://yaaminiv.github.io/SRM-Assay-Day1/) the transition list you're using is final. I must have not updated the predicted retention time document then. I'll update that and close the issue, but the bottom line is that you're not missing peptides!

**Comment by yaaminiv** [comment]
Removed peptides that Emma and i removed from the transition list from predicted retention time document.
