### ISSUE TITLE
Suggestion: rearrange some of the instructions

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/project-oyster-oa#31]
Very minor suggestion, but it might help with clarity!

At the end of Step 3c, you say, "If this is not the case, then the peptide needs to be excluded from the analyses." I then spent some time trying to figure out what you meant and how to do that. 

Then, I decided to just continue reading to see what's going on, and I saw that Step 4b is where the instructions for deleting peptides are.

I would suggest either stating at the end of that sentence in Step 3b that instructions on deleting will come later, or just move the info in 4b to 3c, depending on the importance of the order of Step 4.. 
![capture](https://user-images.githubusercontent.com/14934314/32069273-7b06247e-ba3d-11e7-9a64-e0fbaf759321.PNG)

**Comment by yaaminiv** [comment]
Clarified that instructions for peptide exclusion will come later! Issue resolved.
