### ISSUE TITLE
Suggestion: Rename Raw files

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/project-oyster-oa#32]
At Step 4c, I am instructed to import .raw files numbered 2-137.

This gets a little messy looking for it, so it might makes things easier if they are numbered 002, 003, etc., since it goes up to 3 digits. 
![capture](https://user-images.githubusercontent.com/14934314/32076352-843a19c6-ba54-11e7-9798-60f0cea08059.PNG)

**Comment by yaaminiv** [comment]
Good suggestion! I updated the file names and reorganized them (as suggested in #33), as well as modified the protocol. Can you redownload the raw files and ensure that everything still works/it's clear?

**Comment by grace-ac** [comment]
Successful! Everything still works for Step 4c and is clear.
