### ISSUE TITLE
Step 5b: question

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/project-oyster-oa#33]
Why does the raw folder that we download include blank files if we're just going to end up deleting them in skyline after we upload them?

**Comment by yaaminiv** [comment]
on account of me being lazy and not sorting through all of the raw files and putting them into separate folders. I'll work on it!

**Comment by yaaminiv** [comment]
Reorganized files in OWL. Asked @grace-ac to ensure changes were viable in #32.
