### ISSUE TITLE
Step 5b: 83 and 84 files look weird!

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/project-oyster-oa#34]
I deleted all the blanks.

file 83 and 84 look weird - not sure if they should be removed:
![capture83](https://user-images.githubusercontent.com/14934314/32079140-5d5c35be-ba5e-11e7-8145-8eb14de00a31.PNG)
![capture84](https://user-images.githubusercontent.com/14934314/32079141-5d72d76a-ba5e-11e7-9580-31b6201dbd31.PNG)

**Comment by yaaminiv** [comment]
Looks kind of noisy to me. What does the protocol say about removing peaks?

**Comment by grace-ac** [comment]
That all peptide peaks need to be verified for each sample. 

And since these are just crazy zig zags - not peaks, I removed them.

**Comment by grace-ac** [comment]
And so now, I have to go through each tab. And within each tab, check that each peptide peak looks good.

**Comment by yaaminiv** [comment]
Alright I'll make the protocol more specific. But yeah, removing them is the right call.
