### ISSUE TITLE
Peak question

### ISSUE THREAD

**Issue by grace-ac** [RobertsLab/project-oyster-oa#36]
Some of the peak data are not on the x-axis. Is this okay - or are these samples supposed to be removed? 
![capture](https://user-images.githubusercontent.com/14934314/32118441-9340412c-bb06-11e7-8fae-2578b22cfe7c.PNG)

**Comment by grace-ac** [comment]
hmmm actually maybe most are like this. may have asked this question prematurely.

**Comment by yaaminiv** [comment]
I don't think I understand your question!

**Comment by grace-ac** [comment]
I think I just got confused. 
The intensity (y-axis) for many samples is above 0 and none of them reach zero.

I thought that to create peaks, you had to select the area between where the intensity was zero on either side of the peak. 

But I think that if you zoom in enough on these samples, none of them are at zero.

**Comment by yaaminiv** [comment]
Ah yeah there's always some signal so you won't have anything with a minimum of zero
