### ISSUE TITLE
New boxplots with data points on top

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/project-oyster-oa#37]
[Notebook](https://yaaminiv.github.io/Correlating-Technical-Replicates-Part9/)

[Folder with boxplots](https://github.com/RobertsLab/project-oyster-oa/tree/master/analyses/DNR_SRM_20170902/2017-10-10-Troubleshooting/2017-10-24-Coefficient-of-Variation/2017-10-26-CV-20-Boxplots)

Heat shock protein plots. My two peptides have very different patterns:

![1](https://raw.githubusercontent.com/RobertsLab/project-oyster-oa/master/analyses/DNR_SRM_20170902/2017-10-10-Troubleshooting/2017-10-24-Coefficient-of-Variation/2017-10-26-CV-20-Boxplots/CHOYP_HS12A.25.33.m.60352.APTTLLLEPDGK.y4%20.jpeg)

![2](https://raw.githubusercontent.com/RobertsLab/project-oyster-oa/master/analyses/DNR_SRM_20170902/2017-10-10-Troubleshooting/2017-10-24-Coefficient-of-Variation/2017-10-26-CV-20-Boxplots/CHOYP_HS12A.25.33.m.60352.APTTLLLEPDGK.y6%20.jpeg)

![3](https://raw.githubusercontent.com/RobertsLab/project-oyster-oa/master/analyses/DNR_SRM_20170902/2017-10-10-Troubleshooting/2017-10-24-Coefficient-of-Variation/2017-10-26-CV-20-Boxplots/CHOYP_HS12A.25.33.m.60352.APTTLLLEPDGK.y7%20.jpeg)

![4](https://raw.githubusercontent.com/RobertsLab/project-oyster-oa/master/analyses/DNR_SRM_20170902/2017-10-10-Troubleshooting/2017-10-24-Coefficient-of-Variation/2017-10-26-CV-20-Boxplots/CHOYP_HS12A.25.33.m.60352.GIAEAISSSK.y4%20.jpeg)

![5](https://raw.githubusercontent.com/RobertsLab/project-oyster-oa/master/analyses/DNR_SRM_20170902/2017-10-10-Troubleshooting/2017-10-24-Coefficient-of-Variation/2017-10-26-CV-20-Boxplots/CHOYP_HS12A.25.33.m.60352.GIAEAISSSK.y5%20.jpeg)

![6](https://raw.githubusercontent.com/RobertsLab/project-oyster-oa/master/analyses/DNR_SRM_20170902/2017-10-10-Troubleshooting/2017-10-24-Coefficient-of-Variation/2017-10-26-CV-20-Boxplots/CHOYP_HS12A.25.33.m.60352.GIAEAISSSK.y6%20.jpeg)

How do I move forward? @sr320

**Comment by sr320** [comment]
Pick one peptide for each protein for slides today. We will discuss
afterwards approach going forward.

**Comment by sr320** [comment]
Pick one transition per protein for today’s slides - and we will discuss
afterwards
