### ISSUE TITLE
Peptide-level analyses

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/project-oyster-oa#38]
[Notebook](https://yaaminiv.github.io/Remaining-Analyses-Part2/)

Redid my analyses at the peptide level, still didn't really find anything significant. New boxplots can be found [here](https://github.com/RobertsLab/project-oyster-oa/tree/master/analyses/DNR_SRM_20170902/2017-10-10-Troubleshooting/2017-11-05-Integrated-Dataset/2017-11-06-Boxplots). Should I just run t-tests/ANOVAs to determine if there were any significant differences in protein expression to move forward?

**Comment by sr320** [comment]
Yes - stats should be run..

**Comment by yaaminiv** [comment]
[Notebook](https://yaaminiv.github.io/Remaining-Analyses-Part3/)

![significant](https://raw.githubusercontent.com/RobertsLab/project-oyster-oa/master/analyses/DNR_SRM_20170902/2017-10-10-Troubleshooting/2017-11-05-Integrated-Dataset/2017-11-06-Boxplots/2017-11-06-Annotated-Results.jpeg)

Have some significant peptides. Not sure if there's anything I can do with them before I get environmental data.

**Comment by sr320** [comment]
This would be your story for your WSN talk ... Looks like big difference is
WB and other sites. ID general conditions that are different (not you
should look at buoy data) and for the slides just pic a peptide that is
different per protein.. Come up with explanation and possible implications.

**Comment by yaaminiv** [comment]
> ID general conditions that are different (not you should look at buoy data)

So look at buoy data or not...?

**Comment by sr320** [comment]
- typo not = note
