### ISSUE TITLE
c. gigas transcriptome for PECAN?

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/project-oyster-oa#4]
@sr320 ?

**Comment by sr320** [comment]
Transcriptome or Proteome?

**Comment by sr320** [comment]
Proteome: http://owl.fish.washington.edu/halfshell/bu-git-repos/nb-2017/C_gigas/data/Cg_Gigaton_proteins.fa

Proteome with possible contaminants: http://owl.fish.washington.edu/halfshell/bu-git-repos/nb-2017/C_gigas/data/Cg_Giga_cont_AA.fa

**Comment by yaaminiv** [comment]
oh sorry, proteome! would it be better to use the one with or without contaminants (i'm assuming the one without...?)
