### ISSUE TITLE
Samples with poor technical replication

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/project-oyster-oa#40]
[Notebook](https://yaaminiv.github.io/Remaining-Analyses-Part4/)

Looks like the samples with poor technical replication were run on the first column. The second technical replicate of those samples were the sample we ran before we changed the column. My guess is the technical issue with the column affected those samples before we realized we needed to change the column.

@emmats I can get you 2 of those samples today or tomorrow! When's a good time to drop by Genome Sciences?

**Comment by emmats** [comment]
I need a bit of clarification: Are you saying that samples with poor technical replication had both replicates run on the first column? Or had one replicate run on the first and one of the second column?
Either way, if you are confident that the source of poor replication is the column, then there isn't a reason to rerun your samples. However, if I remember correctly, none of your samples showed the kind of technical replication that we expected so we are actually look at different levels of bad replication. Is that correct? If replicates run on the second column were also less than ideal, then there is still reason to rerun a couple and see if we can do better.

**Comment by yaaminiv** [comment]
Ah my bad for not being clear. The samples with the worst technical replication had both replicates run on the first column. Here's an NMDS to assess technical replication after I removed those samples for peptide-level data:

![NMDS](https://raw.githubusercontent.com/RobertsLab/project-oyster-oa/master/analyses/DNR_SRM_20170902/2017-10-10-Troubleshooting/2017-11-05-Integrated-Dataset/2017-11-05-NMDS-TechnicalReplication-Normalized.jpeg)

How many samples can we rerun?

**Comment by yaaminiv** [comment]
A related question about interpreting these graphs...

I've looked at [Laura's technical replication](https://plot.ly/%7Elhs3/3.embed) and her replication looks good, but her axes are also more zoomed out than mine. So how do we know that mine has poor quality replication and hers doesn't? I'm just trying to understand how to interpret my plots!

**Comment by emmats** [comment]
I don't think your technical replication looks that good, even with the narrowed down dataset.

@laurahspencer dataset does look better, but not all of them do (e.g. 55) and for some (e.g. 54) one of the replicates can be eliminated. How come Laura has 3 reps and you just have 2? Was that just a timing thing.

I don't think "zooming" really has anything to do with it.

Here is an example of what your technical replicates should look like in an SRM dataset. This is from my geoduck gonad analysis.
[tech reps geoduck.pdf](https://github.com/RobertsLab/project-oyster-oa/files/1468254/tech.reps.geoduck.pdf)

**Comment by yaaminiv** [comment]
Gotcha! Can't really speak for Laura's dataset, but thanks for the explanation.

How many samples can I rerun? I'm thinking of rerunning samples that I didn't throw out because of the column, but I can rerun one of those as well just to verify that it was the column...?

**Comment by emmats** [comment]
I think if we rerun 2 it will give us a good idea of whether or not it is worth rerunning the entire set.

**Comment by laurahspencer** [comment]
To answer the rep question:  I re-ran some samples at the end of the Mass spec run b/c there was time, and b/c I observed oddities in some of my samples' PRTC peptides.

**Comment by yaaminiv** [comment]
I'll pick 2 samples that I did not remove/possibly weren't affected by the column change. Can I drop them off with you later today?

**Comment by emmats** [comment]
I'm around. I have a meeting in the early afternoon so text before you come over to make sure I am here.
