### ISSUE TITLE
Fail at step 2d in SRM analysis instructions

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-oyster-oa#8]
When trying to paste proteome in get the follow error.

![image](https://user-images.githubusercontent.com/4442039/31293380-ddf5f346-aa8b-11e7-9048-3c2991c1730d.png)

**Comment by yaaminiv** [comment]
Huh. I can investigate later today. I'm assuming it doesn't resolve itself when you press "OK"?

**Comment by grace-ac** [comment]
Correct @yaaminiv . I'm testing it out and that is the step that got us stuck.

**Comment by sr320** [comment]
Pretty sure it is related to step 2b. 
There is no fasta file provided. 
![image](https://user-images.githubusercontent.com/4442039/31294794-1e9bb908-aa91-11e7-889d-a8327285a026.png)

thus error for 2d. no fasta.

**Comment by yaaminiv** [comment]
http://owl.fish.washington.edu/spartina/DNR_PECAN_Run_1_20170303/Combined-gigas-QC.txt is the file that I used in my DIA analyses as well (nb [here](https://github.com/RobertsLab/project-oyster-oa/blob/master/notebooks/DNR/2017-03-14-Skyline-Test-Run.ipynb))

I'm wondering if just changing the file extension may work....?

**Comment by sr320** [comment]
@emmats 
What are your thoughts on this? Maybe this is cause of issue with replicates.
A tab-delimited text file is being used instead of fasta? Is this possible?


@yaaminiv 
maybe.. but regardless your protocol fails at step 2b as currently written. So make sure you can demonstrate it works (follow your own protocol). I would suggest maybe you did not use this file for SRM as we cannot seem to reproduce (ie get errors)?

**Comment by yaaminiv** [comment]
I'm going to troubleshoot this more today and adjust the protocol so it can be reproduced.

**Comment by emmats** [comment]
Skyline wants fastas, I'm pretty sure.

I don't think this is the problem with the replicates, though.

**Comment by yaaminiv** [comment]
There was a FASTA file on the Windows machine I forgot to upload to OWL. It can now be found [here](http://owl.fish.washington.edu/spartina/DNR_Skyline_20170427/Combined-gigas-QC.fasta).

Additionally, in Step 2d, sometimes copying and pasting the sequences in the lefthand window doesn't work. I've updated the instructions so you can import a FASTA file and populate the analyte tree.  I've also updated the [DIA](https://github.com/RobertsLab/resources/blob/master/protocols/DIA-data-Analyses.md) protocols in RobertsLab/resources with this information (SRM one cites DIA protocol so it doesn't need to be updated).

Your issues should be resolved! I updated my workflow accordingly.
