### ISSUE TITLE
Provide brief explanation for major steps

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-oyster-oa#9]
For example 

Step 2: Create Dilution Curve Skyline Document

Provide a sentence below indicate what this is and why.

**Comment by yaaminiv** [comment]
The purpose of this is to verify that the assay is detecting peptides based on their specific presence in the autosampler vial. We want to ensure that the machine only captures the oyster transitions we set out to measure. The oyster peptide detection should decrease as the concentration in the autosampler vial decreases, and vice versa.

**Comment by sr320** [comment]
to clarify you need to add brief explanation for every major step _in the protocol_.

**Comment by yaaminiv** [comment]
Ohhh, will do!

**Comment by yaaminiv** [comment]
Protocol updated accordingly.
